In [1]:
import numpy as np

## Matrix products

In [2]:
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [6]:
b = np.array([[1,1,1], [1,2,3], [1,4,9]])
b.shape

(3, 3)

In [7]:
# Direct way of multiplying
a.dot(b)

array([[ 6, 17, 34],
       [15, 38, 73]])

In [8]:
# 'Proper' way of multiplying
np.matmul(a,b)

array([[ 6, 17, 34],
       [15, 38, 73]])

## Operations

In [9]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [22]:
# Matrix transpose
A.T

array([[1, 3],
       [2, 4]])

In [10]:
# Inverse matrix
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [12]:
# Matrix deretminant
np.linalg.det(A)

-2.0000000000000004

In [13]:
# Diagonal
np.diag(A)

array([1, 4])

In [14]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [15]:
# Outer/inner product
a = np.array([1,2])
b = np.array([3,4])
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [16]:
np.inner(a,b)

11

In [17]:
a.dot(b)

11

In [18]:
# Matrix trace
np.diag(A).sum()

5

In [19]:
np.trace(A)

5

## Eigenvalues, eigenvectors

In [20]:
X = np.random.randn(100,3)

In [21]:
# Lets try covariance
covvar = np.cov(X)
covvar.shape # <- BAD SHAPE

(100, 100)

In [23]:
# Proper covariance
covvar = np.cov(X.T)
covvar.shape

(3, 3)

In [24]:
covvar

array([[ 0.92129558,  0.05952571,  0.04333649],
       [ 0.05952571,  0.83632018, -0.0535266 ],
       [ 0.04333649, -0.0535266 ,  1.03344261]])

In [26]:
np.linalg.eigh(covvar)

(array([0.78712707, 0.95022503, 1.05370626]),
 array([[-0.46129504,  0.85520966,  0.23626961],
        [ 0.84669925,  0.50390099, -0.17083376],
        [ 0.26515517, -0.12124454,  0.9565524 ]]))

In [27]:
np.linalg.eig(covvar)

(array([0.78712707, 0.95022503, 1.05370626]),
 array([[-0.46129504,  0.85520966,  0.23626961],
        [ 0.84669925,  0.50390099, -0.17083376],
        [ 0.26515517, -0.12124454,  0.9565524 ]]))