In [1]:
import numpy as np

In [2]:
# Simple list
L = [1,2,3]

In [3]:
# Simple numpy array
A = np.array([1,2,3])

In [4]:
# Loop operation
for i in L:
    print(i)

1
2
3


In [5]:
for i in A:
    print(i)

1
2
3


In [6]:
# Append operation
L.append(4)

In [7]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
# Extend the list
L += [4,5]
print(L)

[1, 2, 3, 4, 4, 5]


In [9]:
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
# Adding elements
L2 = []
for e in L:
    L2.append(e+e)
print(L2)

[2, 4, 6, 8, 8, 10]


In [15]:
A+A

array([2, 4, 6])

In [16]:
# Multiplying the array
A*2

array([2, 4, 6])

In [17]:
# Multiplying the list
L*2

[1, 2, 3, 4, 4, 5, 1, 2, 3, 4, 4, 5]

In [18]:
# Square
L2 = []
for e in L:
    L2.append(e*e)

print(L2)

[1, 4, 9, 16, 16, 25]


In [19]:
A**2

array([1, 4, 9])

In [20]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [21]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])