In [1]:
import numpy as np

## Operations

In [2]:
# Simple creation
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# Vector of zeros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
# Uniform distribution
R = np.random.random((10,10))
R

array([[0.56737443, 0.10191897, 0.10074402, 0.51660522, 0.72272106,
        0.57093242, 0.01000777, 0.23729936, 0.94568797, 0.71896072],
       [0.33847289, 0.74211266, 0.64737837, 0.99255225, 0.68882385,
        0.01628607, 0.9144971 , 0.68354129, 0.10045713, 0.6153521 ],
       [0.55485154, 0.48134187, 0.04070786, 0.68247282, 0.65611535,
        0.62679287, 0.37556881, 0.5039565 , 0.81371782, 0.57564016],
       [0.15171105, 0.95852171, 0.32664105, 0.06684218, 0.43007428,
        0.07463236, 0.20258062, 0.69492575, 0.87279907, 0.13232692],
       [0.79604103, 0.29799416, 0.22004628, 0.0607216 , 0.18360621,
        0.93189163, 0.12408724, 0.01837959, 0.84252967, 0.59930195],
       [0.09147304, 0.1585016 , 0.95534615, 0.9027966 , 0.16927827,
        0.88820881, 0.19607761, 0.79332887, 0.64034444, 0.22522134],
       [0.63608276, 0.97347829, 0.50637791, 0.78623473, 0.3805608 ,
        0.23373783, 0.75828321, 0.32822625, 0.88928349, 0.72569094],
       [0.54554818, 0.92294649, 0.5737436

In [6]:
# Gaussian distribution
# miu = 0, sigma = 1
G = np.random.randn(10,10)
G

array([[ 0.30973542, -1.22063851, -0.80691398, -0.37912148, -1.76441304,
         1.10601917,  0.88776825,  0.46385606,  0.45111659,  0.45608388],
       [ 0.24114332,  3.89008802, -0.00687046,  0.70253361,  1.72133691,
         0.71515073,  0.87722827, -0.46054267, -0.39172344,  1.10288064],
       [-0.02532548,  0.96638986,  0.63602553,  0.69102518,  0.4264042 ,
         1.75858275,  0.65728825,  2.57937989,  0.44975352, -0.78172032],
       [-0.02190085, -0.9057834 ,  0.37287863, -0.75343946,  0.6862463 ,
         0.76221577,  0.4241558 , -0.0628631 ,  0.56239924,  1.32245553],
       [ 0.32349127, -0.61297239,  0.54671593,  0.21948917, -0.39751546,
         1.07970352,  0.77952272,  1.89591854, -0.3183551 , -0.68654604],
       [-0.68872166,  0.5139477 ,  1.14543642, -0.98179708, -1.22924584,
         0.71296821,  0.79014134, -0.98892417,  0.64059143,  1.74742873],
       [ 0.98032148, -0.24320874,  1.05767495,  0.41069893, -0.05651421,
         0.37798741, -0.34344193, -2.66173444

In [8]:
# Calculate values
G.mean()

0.2618286310456045

In [9]:
G.var()

1.0129081805539828