In [1]:
import numpy as np

## Linear Problem

In [2]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
b = np.array([1,2])
b

array([1, 2])

In [6]:
# Solution
x = np.linalg.inv(A).dot(b)
x

array([0. , 0.5])

In [7]:
# Proper way of solving
x = np.linalg.solve(A,b)
x

array([0. , 0.5])

In [10]:
# Problem
A = np.array([[1,1], [1.5,4]])
b = np.array([2200, 5050])

In [11]:
np.linalg.solve(A,b)

array([1500.,  700.])